site_name: Azin
site_description: A modern systems programming language.
site_url: https://docs.azin-lang.org
repo_url: https://github.com/azin-lang/azin
repo_name: azin-lang/azin
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: azin
      toggle:
        icon: custom/sun
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: azin-light
      toggle:
        icon: custom/moon
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/azin-lang/azin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HVhCevjAxR
    - icon: fontawesome/solid/newspaper
      link: https://azin-lang.org/blog

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      extend_pygments_lang:
        - name: azin
          lang: rust
        - name: az
          lang: rust
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      toc_depth: '2-6'

nav:
  - Home: index.md
  - Get Started:
      - Overview: get-started/overview.md
      - Installation:
          - Binary Install:
              - Overview: get-started/installation/binary/overview.md
          - Manual Build: get-started/installation/manual-build.md
  - Language:
      - Overview: language/overview.md
      - Syntax:
          - Overview: language/syntax/overview.md
          - Types: language/syntax/types.md
          - Functions: language/syntax/functions.md
          - Variables: language/syntax/variables.md
          - Loops: language/syntax/loop.md
      - Developers:
          - Contribute: language/developers/contribute.md
          - Priorities: language/developers/priorities.md    
  - Standard Library:
      - Overview: std/overview.md
